apiVersion: 1
datasources:
#datasource mimir
  - name: Mimir
    type: prometheus
    access: proxy
    uid: mimir
    orgID: 1
    url: http://nginx:8080/prometheus
    isDefault: true
    jsonData:
      prometheusType: Mimir
      exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger
  - name: Jaeger
    type: jaeger
    access: proxy
    uid: jaeger
    orgID: 1
    url: http://jaeger:16686/

#datasource  loki
  - access: proxy
    basicAuth: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "docker"
    editable: true
    isDefault: false
    name: loki
    type: loki
    uid: loki
    url: http://loki-gateway
    version: 1

  - access: proxy
    basicAuth: false
    editable: true
    isDefault: false
    name: prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    version: 1

#datasource tempo
  # - name: Prometheus
  #   type: prometheus
  #   access: proxy
  #   orgId: 1
  #   url: http://prometheus:9090
  #   basicAuth: false
  #   isDefault: false
  #   version: 1
  #   editable: false
  - name: Tempo
    type: tempo
    access: proxy
    # orgId: 1
    url: http://tempo-query:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
  # - name: Loki
  #   type: loki
  #   access: proxy
  #   orgId: 1
  #   url: http://loki:3100
  #   basicAuth: false
  #   isDefault: false
  #   version: 1
  #   editable: false
  #   apiVersion: 1
  #   jsonData:
  #     derivedFields:
  #       - datasourceUid: tempo
  #         matcherRegex: (?:traceID|trace_id)=(\w+)
  #         name: TraceID
  #         url: $${__value.raw}